### ISSUE TITLE
django.core.exceptions.FieldError

### ISSUE THREAD

**Issue by amirasaad** [grvty-labs/django-openpay#1]
`$  ./manage.py makemigrations `

# Full Traceback 

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/amir/Envs/lbs4biz_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/amir/Envs/lbs4biz_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/amir/Envs/lbs4biz_env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/amir/Envs/lbs4biz_env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/amir/Envs/lbs4biz_env/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/amir/Envs/lbs4biz_env/local/lib/python2.7/site-packages/django_openpay/models.py", line 56, in <module>
    class Address(AbstractOpenpayBase):
  File "/home/amir/Envs/lbs4biz_env/local/lib/python2.7/site-packages/django/db/models/base.py", line 223, in __new__
    'base class %r' % (field.name, name, base.__name__)
django.core.exceptions.FieldError: Local field 'creation_date' in class 'Address' clashes with field of similar name from base class 'AbstractOpenpayBase'
```

**Comment by letops** [comment]
Apparently since Django 1.10 you can override some fields, and this is why we haven't had this issue in our repositories. We will confirm this theory in a couple of hours. But we recommend to use the newest versions of Django to prevent this issue from happening.
